name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    if: github.repository == 'yusuke99/bulk-nerd-fonts'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --access public --no-git-checks

  release:
    needs: publish
    if: github.repository == 'yusuke99/bulk-nerd-fonts'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          next_version=$(jq -r '.version' package.json | sed 's/^/v/')

          gh release create "$next_version" \
          --title "$next_version" \
          --generate-notes
